services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="Payever-DB"
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
